--- #YAML:1.0
name:                WWW-SchneierFacts
version:             0.02
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Moose:                         0
    namespace::clean:              0.08
    Test::use::ok:                 0
    URI:                           0
    Web::Scraper:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
